rules:
  - package: a
    illegal_dependencies:
      - fmt
      - math/rand
      - net/*
  - package: a/b
    illegal_dependencies:
      - log
      - math/rand
      - net/*
  - package: "**/c/**/*"
    illegal_dependencies:
      - log
      - math/rand
      - net/*
